services:
    hezten_timetable.subjecttimetable_manager.default:
         class: "Hezten\TimetableBundle\EntityManager\SubjectTimetableManager"
         arguments: [@doctrine.orm.entity_manager, %hezten_timetable.subjecttimetable_class%]
