parameters:
#    timetable.example.class: SanFidel\TimetableBundle\Example

services:
#    timetable.example:
#        class: %timetable.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
